spring.application.name=blogPlatform

server.port=${PORT:8080}

# Database

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Cloudinary

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Gemini (OpenAI Compatible)

spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=${GEMINI_BASE_URL}
spring.ai.openai.chat.options.model=${GEMINI_MODEL}
